# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nic/Documents/Projects/C/FishAndChippie8

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nic/Documents/Projects/C/FishAndChippie8

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nic/Documents/Projects/C/FishAndChippie8/CMakeFiles /home/nic/Documents/Projects/C/FishAndChippie8//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nic/Documents/Projects/C/FishAndChippie8/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nic/Documents/Projects/C/FishAndChippie8/CMakeFiles /home/nic/Documents/Projects/C/FishAndChippie8//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nic/Documents/Projects/C/FishAndChippie8/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FishAndChippie8

# Build rule for target.
FishAndChippie8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FishAndChippie8
.PHONY : FishAndChippie8

# fast build rule for target.
FishAndChippie8/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/build
.PHONY : FishAndChippie8/fast

src/audio/audio.o: src/audio/audio.c.o
.PHONY : src/audio/audio.o

# target to build an object file
src/audio/audio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/audio/audio.c.o
.PHONY : src/audio/audio.c.o

src/audio/audio.i: src/audio/audio.c.i
.PHONY : src/audio/audio.i

# target to preprocess a source file
src/audio/audio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/audio/audio.c.i
.PHONY : src/audio/audio.c.i

src/audio/audio.s: src/audio/audio.c.s
.PHONY : src/audio/audio.s

# target to generate assembly for a file
src/audio/audio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/audio/audio.c.s
.PHONY : src/audio/audio.c.s

src/cpu/cpu.o: src/cpu/cpu.c.o
.PHONY : src/cpu/cpu.o

# target to build an object file
src/cpu/cpu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/cpu/cpu.c.o
.PHONY : src/cpu/cpu.c.o

src/cpu/cpu.i: src/cpu/cpu.c.i
.PHONY : src/cpu/cpu.i

# target to preprocess a source file
src/cpu/cpu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/cpu/cpu.c.i
.PHONY : src/cpu/cpu.c.i

src/cpu/cpu.s: src/cpu/cpu.c.s
.PHONY : src/cpu/cpu.s

# target to generate assembly for a file
src/cpu/cpu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/cpu/cpu.c.s
.PHONY : src/cpu/cpu.c.s

src/display/display.o: src/display/display.c.o
.PHONY : src/display/display.o

# target to build an object file
src/display/display.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/display/display.c.o
.PHONY : src/display/display.c.o

src/display/display.i: src/display/display.c.i
.PHONY : src/display/display.i

# target to preprocess a source file
src/display/display.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/display/display.c.i
.PHONY : src/display/display.c.i

src/display/display.s: src/display/display.c.s
.PHONY : src/display/display.s

# target to generate assembly for a file
src/display/display.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/display/display.c.s
.PHONY : src/display/display.c.s

src/keypad/keypad.o: src/keypad/keypad.c.o
.PHONY : src/keypad/keypad.o

# target to build an object file
src/keypad/keypad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/keypad/keypad.c.o
.PHONY : src/keypad/keypad.c.o

src/keypad/keypad.i: src/keypad/keypad.c.i
.PHONY : src/keypad/keypad.i

# target to preprocess a source file
src/keypad/keypad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/keypad/keypad.c.i
.PHONY : src/keypad/keypad.c.i

src/keypad/keypad.s: src/keypad/keypad.c.s
.PHONY : src/keypad/keypad.s

# target to generate assembly for a file
src/keypad/keypad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/keypad/keypad.c.s
.PHONY : src/keypad/keypad.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/main.c.s
.PHONY : src/main.c.s

src/memory/memory.o: src/memory/memory.c.o
.PHONY : src/memory/memory.o

# target to build an object file
src/memory/memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/memory/memory.c.o
.PHONY : src/memory/memory.c.o

src/memory/memory.i: src/memory/memory.c.i
.PHONY : src/memory/memory.i

# target to preprocess a source file
src/memory/memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/memory/memory.c.i
.PHONY : src/memory/memory.c.i

src/memory/memory.s: src/memory/memory.c.s
.PHONY : src/memory/memory.s

# target to generate assembly for a file
src/memory/memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/memory/memory.c.s
.PHONY : src/memory/memory.c.s

src/system/system.o: src/system/system.c.o
.PHONY : src/system/system.o

# target to build an object file
src/system/system.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/system/system.c.o
.PHONY : src/system/system.c.o

src/system/system.i: src/system/system.c.i
.PHONY : src/system/system.i

# target to preprocess a source file
src/system/system.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/system/system.c.i
.PHONY : src/system/system.c.i

src/system/system.s: src/system/system.c.s
.PHONY : src/system/system.s

# target to generate assembly for a file
src/system/system.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FishAndChippie8.dir/build.make CMakeFiles/FishAndChippie8.dir/src/system/system.c.s
.PHONY : src/system/system.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FishAndChippie8"
	@echo "... src/audio/audio.o"
	@echo "... src/audio/audio.i"
	@echo "... src/audio/audio.s"
	@echo "... src/cpu/cpu.o"
	@echo "... src/cpu/cpu.i"
	@echo "... src/cpu/cpu.s"
	@echo "... src/display/display.o"
	@echo "... src/display/display.i"
	@echo "... src/display/display.s"
	@echo "... src/keypad/keypad.o"
	@echo "... src/keypad/keypad.i"
	@echo "... src/keypad/keypad.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/memory/memory.o"
	@echo "... src/memory/memory.i"
	@echo "... src/memory/memory.s"
	@echo "... src/system/system.o"
	@echo "... src/system/system.i"
	@echo "... src/system/system.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

